a = int(input("Enter a: "))
b = int(input("Enter b: "))

print(int(a), end=' ')
print("+", end=' ')
print(int(b), end=' ')
print("=", end=' ')
print(int(a) + int(b))
print(int(a), end=' ')
print("*", end=' ')
print(int(b), end=' ')
print("=", end=' ')
print(int(a) * int(b))